import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './component/Navbar/Navbar'
import Footer from './component/Footer/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Village Square Pharmacy',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
<html lang="en">
  <body className={inter.className} style={{ display: "grid", gridTemplateRows: "auto 1fr auto", minHeight: "100vh" }}>
    <Navbar />
    <div className="mx-4">
      {children}
    </div>
    <Footer />
  </body>
</html>
  )
}
